backend:
  name: github
  repo: Potentialbeliever/aso-college-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://asocos.com
display_url: https://asocos.com

collections:
  - label: "Gallery"
    name: "gallery"
    files:
      - label: "Gallery Items"
        name: "items"
        file: "data/gallery.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text", required: false }
